version: "3.6"
x-chainlink-def:
  &chainlink-def
  image: public.ecr.aws/chainlink/chainlink:1.3.0
  #image: agoric/chainlink:hacktheorb
  restart: on-failure
  secrets:
    - node_password
    - apicredentials
  env_file:
    - ./chainlink.env
  command: 'node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials'
x-postgres-def:
  &postgres-def
  image: agoric/postgres:hacktheorb
  restart: on-failure
  environment:
    - "POSTGRES_MULTIPLE_DATABASES=chainlink,ei"
    - "POSTGRES_HOST_AUTH_METHOD=trust"
services:
  chainlink-node1:
    <<: *chainlink-def
    depends_on:
      - postgres-node1
    ports:
      - "6691:6688"
    environment:
      - "DATABASE_URL=postgresql://chainlink@chainlink-agoric_postgres-node1_1:5432/chainlink?sslmode=disable"
    volumes:
      - 'cl1:/chainlink'
  postgres-node1:
    <<: *postgres-def
    volumes:
      - './docker-init-scripts:/docker-entrypoint-initdb.d'
      - 'pg1:/var/lib/postgresql/data'
volumes:
  pg1:
  cl1:
  ag1:
  pg2:
  cl2:
  ag2:
  pg3:
  cl3:
  ag3:
secrets:
  node_password:
    file: ./secrets/password.txt
  apicredentials:
    file: ./secrets/apicredentials
