#!/bin/bash

EMAIL=$1
PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 15)
PASSWORD=$(echo $PASSWORD | tr '[:lower:]' '[:upper:]' | sed -E 's/(.)/\1\n/g' | shuf | tr -d '\n')

echo $EMAIL > secrets/apicredentials
echo $PASSWORD >> secrets/apicredentials
echo "CL Node password: $PASSWORD"

thisdir=$(dirname -- "$BASH_SOURCES[0]")
cd "$thisdir" || exit $?

source ./internal-scripts/common.sh

run_setup() {

  touch external_initiator1.env

  start_docker 300 1

  source ./internal-scripts/add-ei.sh

  add_ei "1"

  source ./internal-scripts/add-bridge.sh

  add_bridge "1"

}

run_setup ${1+"$1"}
