#!/bin/bash

thisdir=$(dirname -- "$BASH_SOURCES[0]")
cd "$thisdir" || exit $?

source ./internal-scripts/common.sh

run_setup() {

  touch external_initiator1.env

  start_docker 300 1

  source ./internal-scripts/add-ei.sh

  add_ei "1"

  source ./internal-scripts/add-bridge.sh

  add_bridge "1"

}

run_setup ${1+"$1"}
